"""Generate docs/data_dictionary.md from the PostgreSQL catalogue.

The descriptions come from the COMMENT ON statements in sql/05_comments.sql, so the
dictionary always matches the database. Run after the warehouse has been built:

    python tools/generate_data_dictionary.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from db import get_connection  # noqa: E402

OUT = ROOT / "docs" / "data_dictionary.md"
SCHEMA = "dw"

GROUPS = [
    ("Dimensions", "dim_"),
    ("Facts", "fact_"),
    ("Analytical views", "vw_"),
    ("Traceability", "etl_"),
]

TABLE_SQL = """
SELECT c.relname, c.relkind, obj_description(c.oid, 'pg_class')
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = %s AND c.relkind IN ('r', 'v')
ORDER BY c.relname
"""

COLUMN_SQL = """
SELECT a.attname,
       pg_catalog.format_type(a.atttypid, a.atttypmod),
       NOT a.attnotnull,
       col_description(a.attrelid, a.attnum)
FROM pg_attribute a
WHERE a.attrelid = %s::regclass AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
"""

KEYS_SQL = """
SELECT kcu.column_name, tc.constraint_type, ccu.table_name, ccu.column_name
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
  ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
LEFT JOIN information_schema.constraint_column_usage ccu
  ON tc.constraint_type = 'FOREIGN KEY' AND tc.constraint_name = ccu.constraint_name
WHERE tc.table_schema = %s AND tc.table_name = %s
"""


def table_block(cur, name: str, kind: str, description: str) -> list[str]:
    keys: dict[str, str] = {}
    if kind == "r":
        cur.execute(KEYS_SQL, (SCHEMA, name))
        for col, ctype, ref_table, ref_col in cur.fetchall():
            keys[col] = "PK" if ctype == "PRIMARY KEY" else (f"FK -> {ref_table}" if ctype == "FOREIGN KEY" else keys.get(col, ""))
    cur.execute(COLUMN_SQL, (f"{SCHEMA}.{name}",))
    rows = cur.fetchall()
    lines = [f"### `{SCHEMA}.{name}`", "", description or "", "",
             "| Column | Type | Null | Key | Description |", "|---|---|---|---|---|"]
    for col, dtype, nullable, comment in rows:
        text = (comment or "").replace("|", "/")
        lines.append(f"| `{col}` | {dtype} | {'yes' if nullable else 'no'} | {keys.get(col, '')} | {text} |")
    return lines + [""]


def main() -> None:
    cx = get_connection()
    with cx.cursor() as cur:
        cur.execute(TABLE_SQL, (SCHEMA,))
        tables = cur.fetchall()
        lines = [
            "# Data dictionary",
            "",
            "Generated by `tools/generate_data_dictionary.py` from the PostgreSQL catalogue "
            "(descriptions live in `sql/05_comments.sql`). Do not edit by hand.",
            "",
            "Geographic unit: urban AGEB (`dim_ageb`). Storage CRS: EPSG:4326. Metric CRS: EPSG:32614 (UTM 14N).",
            "Sources: Census 2020 (population), DENUE 11/2024 (establishments), FGJ CDMX 2024 (crime), INEGI Marco Geoestadistico 2020 (polygons).",
            "",
            "Model diagram: [warehouse_model.png](warehouse_model.png)",
            "",
        ]
        for title, prefix in GROUPS:
            group = [t for t in tables if t[0].startswith(prefix)]
            if not group:
                continue
            lines += [f"## {title}", ""]
            for name, kind, desc in group:
                lines += table_block(cur, name, kind, desc)
    cx.close()
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(tables)} tables and views)")


if __name__ == "__main__":
    main()
